# Generated by Django 6.0.3 on 2026-03-16 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('jobs', '0002_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_skills', to='jobs.skill'),
        ),
    ]
